workflows:
  ios-workflow:
    name: SnapShe iOS Build

    environment:
      xcode: latest
      cocoapods: default

      vars:
        BUNDLE_ID: "com.snapshe.app"
        XCODE_PROJECT: "SnapShe.xcodeproj"
        XCODE_SCHEME: "SnapShe"
        APP_STORE_APPLE_ID: "6760227147"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.snapshe.app

    triggering:
      events:
        - push

    scripts:

      - name: Set app version
        script: |
          cd $CM_BUILD_DIR

          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.2" SnapShe/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion 3" SnapShe/Info.plist

      - name: Install CocoaPods
        script: |
          cd $CM_BUILD_DIR
          pod install || true

      - name: Create Export Options
        script: |
          cd $CM_BUILD_DIR

          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>

              <key>signingStyle</key>
              <string>automatic</string>

              <key>stripSwiftSymbols</key>
              <true/>

              <key>compileBitcode</key>
              <false/>

              <key>uploadBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF

      - name: Build IPA
        script: |
          cd $CM_BUILD_DIR

          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "$CM_BUILD_DIR/export_options.plist"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        submit_to_testflight: true
        submit_to_app_store: false
